### sample-chat
GET localhost:8080/api/v1/ollama/sample-chat
Authorization: Bearer {{token}}

### stream-chat
GET localhost:8080/api/v1/ollama/stream-chat

### image2text for caobaoqi6040
#GET localhost:8080/api/v1/ollama/image2text?img-url=http://192.168.112.167:9001/api/v1/download-shared-object/aHR0cDovLzEyNy4wLjAuMTo5MDAwL3NwcmluZy1haS1zYW1wbGUvY2FvYmFvcWk2MDQwLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPTNJRzVBVkM3U0lXVUFGQzRIRDJOJTJGMjAyNTA5MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwOTE5VDAzMjYwM1omWC1BbXotRXhwaXJlcz00MzE5OSZYLUFtei1TZWN1cml0eS1Ub2tlbj1leUpoYkdjaU9pSklVelV4TWlJc0luUjVjQ0k2SWtwWFZDSjkuZXlKaFkyTmxjM05MWlhraU9pSXpTVWMxUVZaRE4xTkpWMVZCUmtNMFNFUXlUaUlzSW1WNGNDSTZNVGMxT0RJNU5EYzVOU3dpY0dGeVpXNTBJam9pYldsdWFXOGlmUS5wNHQtX2xHTC16dnkyWmxMZFN4T3RjTG5oTlZyT1AwazJuNnlmMi1qVWl5VDVfTVlPaGZJZFJfeGlNWUFOUzBNeGcwbDZlWlZZN1JHQS1KdkpEU3Q3QSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmdmVyc2lvbklkPW51bGwmWC1BbXotU2lnbmF0dXJlPWUzMjM1YWEwNDQ4MzJiMTNlY2Y4NDM1YjBkMTk4OGM3MTM0YjIyZTM3NmY5MWFkZjNhNjUyMWEwZDdiNDFkM2Q
GET localhost:8080/api/v1/ollama/image2text?
    img-url=http://192.168.112.167:9001/api/v1/download-shared-object/aHR0cDovLzEyNy4wLjAuMTo5MDAwL3NwcmluZy1haS1zYW1wbGUvYmFja2dyb3VuZC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD0zSUc1QVZDN1NJV1VBRkM0SEQyTiUyRjIwMjUwOTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDkxOVQwMzI5NTlaJlgtQW16LUV4cGlyZXM9NDMyMDAmWC1BbXotU2VjdXJpdHktVG9rZW49ZXlKaGJHY2lPaUpJVXpVeE1pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SmhZMk5sYzNOTFpYa2lPaUl6U1VjMVFWWkROMU5KVjFWQlJrTTBTRVF5VGlJc0ltVjRjQ0k2TVRjMU9ESTVORGM1TlN3aWNHRnlaVzUwSWpvaWJXbHVhVzhpZlEucDR0LV9sR0wtenZ5MlpsTGRTeE90Y0xuaE5Wck9QMGsybjZ5ZjItalVpeVQ1X01ZT2hmSWRSX3hpTVlBTlMwTXhnMGw2ZVpWWTdSR0EtSnZKRFN0N0EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JnZlcnNpb25JZD1udWxsJlgtQW16LVNpZ25hdHVyZT03NjE1MDliNzM3YmZhYmYyYzI1MDQ5M2NiZWQzNDJhYTJhMjAxMjQ5MGRiOWI1Nzc4YWU3M2RhNWZmOWUzYTI2

